# Generated by Django 5.2.5 on 2025-09-07 05:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_hira', models.CharField(max_length=100)),
                ('word_kanji', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_mode', models.CharField(choices=[('kanji', 'Kanji'), ('no_kanji', 'No Kanji')], max_length=10)),
                ('sentence', models.TextField()),
                ('options', models.JSONField()),
                ('answer', models.CharField(max_length=100)),
                ('explanation', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='ai_content.vocabulary')),
            ],
        ),
    ]
