# Generated by Django 5.2.5 on 2025-09-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
